hello.exception.HelloException=エラーが発生しました
